/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioLogin = new javax.swing.JTextField();
        contraseñaLogin = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioLogin.setBackground(new java.awt.Color(204, 204, 255));
        usuarioLogin.setText("Usuario");
        usuarioLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioLoginMousePressed(evt);
            }
        });
        getContentPane().add(usuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 313, 240, 33));

        contraseñaLogin.setBackground(new java.awt.Color(204, 204, 255));
        contraseñaLogin.setText("Contraseña");
        contraseñaLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaLoginMousePressed(evt);
            }
        });
        contraseñaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaLoginActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 383, 242, 33));

        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginMousePressed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 150, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Login/pgLogin.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaLoginActionPerformed

    private void loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMousePressed
        VentanaPrincipal m = new VentanaPrincipal();
	m.setVisible(true);
	this.setVisible(false);
    }//GEN-LAST:event_loginMousePressed

    private void usuarioLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioLoginMousePressed
        if(usuarioLogin.getText().equals("Usuario")){
	    usuarioLogin.setText("");
	}
    }//GEN-LAST:event_usuarioLoginMousePressed

    private void contraseñaLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaLoginMousePressed
        if(contraseñaLogin.getText().equals("Contraseña")){
	    contraseñaLogin.setText("");
	}
    }//GEN-LAST:event_contraseñaLoginMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Login().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contraseñaLogin;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton login;
    private javax.swing.JTextField usuarioLogin;
    // End of variables declaration//GEN-END:variables
}
